#!/usr/bin/python
import sys
import encryption

if __name__ == "__main__":
    try:
        text = sys.argv[3]
    except(IndexError):
        text = input()
    shift = int(sys.argv[2])
    if sys.argv[1]=="-e":
        print(encryption.encrypt(text,shift))
    elif sys.argv[1]=="-d" : 
        print(encryption.decrypt(text,shift))
